import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './ui/footer';
import Header from './ui/header';
import Navbar from './ui/navbar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-screen`}>
        <main className="flex min-h-screen flex-col">
          <Navbar />
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
